### ISSUE TITLE
Log file string

### ISSUE THREAD

**Issue by zortag** [QModManager/QModManager#294]
i'm trying to mod subnautica below zero and i installed qmod as requested for some mod.
in the log file i get a red string about a missing dll

[Error  :QModPluginGenerator] Could not find QMM assembly: D:\Steam\steamapps\common\SubnauticaZero\BepInEx\patchers\QModManager\QModManager.OculusNewtonsoftRedirect.dll

the other mods are BepInEx and Nautilus, all mods are actually latest version, like the game

**Comment by kai-bat** [comment]
QModManager currently only works for the legacy branch of subnautica, it and any mods requiring it don't work on the latest version of subnautica

**Comment by zortag** [comment]
damn... thank you... it is planned an update or the game is too old at now?

**Comment by kai-bat** [comment]
QModManager and smlhelper wont be updated, mods will need to be updated by their respective authors to work with bepinex and nautilus (the new version of smlhelper). 

Even if QModManager was updated, the individual mods would need to be updated to work on the new version of the game because the developers changed a bunch of stuff in their code with the living large update

**Comment by kai-bat** [comment]
Many mods have already been updated to work on bepinex, some of them just got re-uploaded as new mods on nexus so you may need to go searching for them

**Comment by zortag** [comment]
Thank you, i'm new on Subnautica franchise so i need to know more about modding it

**Comment by kai-bat** [comment]
I recommend that you join the subnautica modding discord, linked in the main page of QModManager on GitHub

**Comment by toebeann** [comment]
That particular line in your logs won't have any affect on whether QModManager (QMM) or mods are working properly. The mentioned assembly file was removed from QMM in an update and the maintainers at the time forgot to remove the reference to it, which causes the error message to come up in users' log files, but doesn't actually cause any problems with how QMM operates.

kai-bat is unfortunately misguiding you slightly here, as they have not seemed to notice that you are talking about using QMM with Subnautica: Below Zero, not Subnautica. QMM _does_ work on the latest version of Below Zero (BZ). It's only the latest version of Subnautica which it does not work for, because of the Living Large update which was released to Subnautica on  December 14th, 2022, after which QModManager was summarily discontinued in favour of using BepInEx. Because of this, with Subnautica you now have to choose between using QMM on the Steam legacy branch (the old game version which QMM last worked with), or BepInEx on the latest standard version of Subnautica. When modding BZ however, you can use both QMM and BepInEx mods together, because there has been no QModManager-breaking update to BZ since QMM's discontinuation.

The main thing to watch out for which is true for both games is that you should not use both SMLHelper and Nautilus together.

If you are having problems with mods for either game, as kai said it is probably best to join the discord and ask for help with the specific issues you are running into there, where there is a dedicated help-and-support channel for users to ask for help with their installation issues and using mods in general. GitHub issue pages like this are generally intended to be used by developers.
