### ISSUE TITLE
Can't resolve identical EntryMethods

### ISSUE THREAD

**Issue by lPVDl** [QModManager/QModManager#51]
**Describe the bug**
If two or more mods will have same "EntryMethod", then QModManager  will report error:
> _QMOD ERR: something strange happened_

and will not load mods.

**Additional info**
I want to use same entry method ("_QMod.Patch_") for all my libraries, is there a way QModManager can deal with it?

**Comment by PrimeSonic** [comment]
Are you also using the exact same namespace in all those libraries?  
Because I also use the exact same method name for all my EntryMethods without issue, since they disambiguate via the namespace.

_Example_
#### [MoreCyclopsUpgrades](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/tree/master/MoreCyclopsUpgrades)
[QPatch class](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/blob/master/MoreCyclopsUpgrades/QPatch.cs) uses `Patch()` method.
[mod.json](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/blob/master/MoreCyclopsUpgrades/mod.json) shows `"EntryMethod": "MoreCyclopsUpgrades.QPatch.Patch",`

#### [VModFabricator](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/tree/master/VModFabricator)
[QPatch class](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/blob/master/VModFabricator/QPatch.cs) uses `Patch()` method  
[mod.json](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/blob/master/VModFabricator/mod.json) shows `"EntryMethod": "VModFabricator.QPatch.Patch",`

This works just fine.  
Could you provide more detail or examples of what you're trying to do.

**Comment by kylinator25** [comment]
You would not be able to have the same class name twice in the same namespace anyway, if you dont differentiate your libraries with a namespace, then two classes with the same name would cause a conflict wouldn't they?

**Comment by PrimeSonic** [comment]
> You would not be able to have the same class name twice in the same namespace anyway, if you dont differentiate your libraries with a namespace, then two classes with the same name would cause a conflict wouldn't they?

Until @lPVDl confirms, my only assumption is that they are most likely creating each mod in its own separate Solution instead of having them as multiple Projects of the same Solution.  
When done like this, the namespaces would never encounter each other since their assemblies would never have to compile in the same environment.

However, once the DLLs make their way into QModManager, they will then encounter each other at run time. And there is where the problem could happen if they share the exact same namespaces.

**Comment by lPVDl** [comment]
> You would not be able to have the same class name twice in the same namespace anyway, if you dont differentiate your libraries with a namespace, then two classes with the same name would cause a conflict wouldn't they?

There are two projects in same solution. Entry points have same namespace, same class name and same method name. Second project has first in the references. Compilation works fine.

![devenv_2019-02-12_00-22-30](https://user-images.githubusercontent.com/5685763/52597702-589c0680-2e5c-11e9-98b0-a944a2b52b70.png)

**Comment by lPVDl** [comment]
> Until @lPVDl confirms, my only assumption is that they are most likely creating each mod in its own separate Solution instead of having them as multiple Projects of the same Solution.
When done like this, the namespaces would never encounter each other since their assemblies would never have to compile in the same environment.

![devenv_2019-02-12_00-30-12](https://user-images.githubusercontent.com/5685763/52598059-6bfba180-2e5d-11e9-9a8e-a2fb67fa41a7.png)

**Comment by kylinator25** [comment]
Yea its not generally good to have two projects in VS using the same namespace, you are bound to run into errors at runtime if they have identical class names

**Comment by PrimeSonic** [comment]
Are you able to call both of these `Patch()` methods from the same class, independently, and _without_ using namespace aliases? Because that is what QModManager has to do.  
You're free to submit a Pull Request with a proposed solution to this, if you can find one.

Otherwise, I would recommend that you follow the general template guidelines for namespaces and use something more meaningful and distinct.
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces
> X DO NOT give the same name to types in namespaces within a single application model.
> For example, do not add a type named `Page` to the `System.Web.UI.Adapters` namespace, because the `System.Web.UI` namespace already contains a type named `Page`.

In your case, you are defining the same class twice within the same namespace, against all best practices and recommendations.

**Comment by lPVDl** [comment]
> In your case, you are defining the same class twice within the same namespace, against all best practices and recommendations.

May not agree with that completely. Since QMod class is just reflection based class, which is supposed to be called only from one external library, once. Anyway, the main reason for this is just simplicity. For example, you open of bunch code and you clearly see the entrance point (sure you can look mod.json, but remember that this file is not directly linked to your project).

> You're free to submit a Pull Request with a proposed solution to this, if you can find one.

Okay.

**Comment by AlexejheroYTB** [comment]
Please install the 1.4 version available [here](https://github.com/qmodmanager/qmodmanager/blob/master/Installer/QModManager_Setup.exe) and try again

**Comment by lPVDl** [comment]
> Please install the 1.4 version available [here](https://github.com/qmodmanager/qmodmanager/blob/master/Installer/QModManager_Setup.exe) and try again.
That version has far more logging

It throws _NullReferenceException_ and then over flood log file with message:

> NullReferenceException
 at (wrapper managed-to-native) UnityEngine.Component:get_transform ()
 at WaterSurface.UpdateClipCamera () [0x00000] in <filename unknown>:0 
 at WaterSurface.DoUpdate () [0x00000] in <filename unknown>:0 
 at WaterSurfaceOnCamera.OnPostRender () [0x00000] in <filename unknown>:0 
(Filename: Line: -1)

[QMod_1.4_log.mp4.zip](https://github.com/QModManager/QModManager/files/2861765/QMod_1.4_log.mp4.zip)

**Comment by AlexejheroYTB** [comment]
☠️

**Comment by AlexejheroYTB** [comment]
I didn't think I would need to say this soo soon after release, but QModManager no longer supports pirated versions of the game. Also 2.0 was released a few minutes ago

**Comment by lPVDl** [comment]
> QModManager no longer supports pirated versions of the game

What for?

Tried steam version, SMLHelper works fine. My mod is not launching (it is empty mod with no harmony patches).

[output_log.txt](https://github.com/QModManager/QModManager/files/2862091/output_log.txt)
[AGUtils.zip](https://github.com/QModManager/QModManager/files/2862092/AGUtils.zip)

**Comment by AlexejheroYTB** [comment]
You need to specify the namespace too, so `Agony.AGUtilsQMod.Patch`, not `AGUtilsQMod.Patch`

**Comment by AlexejheroYTB** [comment]
The namespace is currently required, but this might change in the next version, making it optional

**Comment by lPVDl** [comment]
> You need to specify the namespace too, so `Agony.AGUtilsQMod.Patch`, not `AGUtilsQMod.Patch`

Oh yes, see. Forgot to modify _mod.json_. Anyway isn't QMod supposed to tell that "EntryMethod" is not found?

I have tried to have same "EntryMethod" in each library and it... works. Great job!
